name: CI for ball_blast

on:
  push:
    paths:
      - 'apps/ball_blast/**'
      - '.github/workflows/ball_blast-ci.yml'
  pull_request:
    paths:
      - 'apps/ball_blast/**'
      - '.github/workflows/ball_blast-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx nx build ball_blast
      - name: Upload dist
        uses: actions/upload-artifact@4
        with:
          name: dist-ball_blast
          path: dist/apps/ball_blast 