name: CI

on:
    push:
        branches:
            - master
    pull_request:

permissions:
    actions: read
    contents: read

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - run: npm ci --legacy-peer-deps

            # Ensure peer dependencies are correctly installed
            - run: npm list || echo "Dependency issues detected, please check package.json"

            - uses: nrwl/nx-set-shas@v4

            # Build the project
            - run: npx nx affected -t build

            # Debug: Check where the artifacts are
            - run: ls -R dist

            # Upload build artifacts
            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: game-hub-build
                  path: dist/
