name: CI-CD - Deploy Changed MFEs & Shell

on:
  push:
    branches:
      - master

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      affected_apps: ${{ steps.set-affected.outputs.affected_apps }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4

      # Get affected apps (only those that have changed)
      - name: Get Affected Apps
        id: set-affected
        run: echo "affected_apps=$(npx nx print-affected --type=app --select=projects)" >> $GITHUB_ENV

      # Debug: Show affected apps
      - run: echo "Affected Apps: $affected_apps"

      # Build only the affected apps
      - run: npx nx affected -t build --exclude=libs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(env.affected_apps) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy ${{ matrix.app }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets[format('AZURE_STATIC_WEB_APPS_API_TOKEN_{0}', matrix.app)] }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist/apps/${{ matrix.app }}"
          output_location: ""
