name: CI

on:
    push:
        branches:
            - master
    pull_request:

permissions:
    actions: read
    contents: read

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - run: npm ci --legacy-peer-deps

            # Ensure peer dependencies are correctly installed
            - run: npm list || echo "Dependency issues detected, please check package.json"

            - uses: nrwl/nx-set-shas@v4

            # Lint and automatically fix issues before failing
            - run: npx nx affected -t lint --fix
              continue-on-error: true
            # Fail fast if linting fails
            - run: npx nx affected -t lint
              continue-on-error: true

            # Run tests
            - run: npx nx affected -t test

            # Build the project
            - run: npx nx affected -t build
